# Generated by Django 4.2.5 on 2023-10-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
